version: "3.1"
services:
  merlin-naemon:
    volumes:
      - ipc:/var/lib/merlin/
      - merlin_config:/etc/merlin/
    image: op5com/merlin-naemon:latest
    environment:
      # Needed for automatically adding the new poller to the cluster
      MASTER_ADDRESS:
      MASTER_NAME:
      MASTER_PORT:
      POLLER_ADDRESS:
      POLLER_NAME:
      POLLER_HOSTGROUPS:
      LOG_LEVEL: "info" # debug, info (default), error, critical
      FILES_TO_SYNC:
  merlin-daemon:
    volumes:
      - ipc:/var/lib/merlin/
      - merlin_config:/etc/merlin/
    image: op5com/merlin-daemon:latest
volumes:
  ipc:
  merlin_config:
