version: "3.1"
services:
  merlin-base:
    build:
      dockerfile: ./base/Dockerfile
      context: ./images
    container_name: merlin-base
    image: op5com/merlin-base
  merlin-naemon:
    build:
      dockerfile: ./naemon/Dockerfile
      context: ./images
    volumes:
      - ipc:/var/lib/merlin/
      - merlin_config:/etc/merlin/
    image: op5com/merlin-naemon
    environment:
      # Needed for automatically adding the new poller to the cluster
      MASTER_ADDRESS:
      MASTER_NAME:
      MASTER_PORT:
      POLLER_ADDRESS:
      POLLER_NAME:
      POLLER_HOSTGROUPS:
  merlin-daemon:
    build:
      dockerfile: ./daemon/Dockerfile
      context: ./images
    volumes:
      - ipc:/var/lib/merlin/
      - merlin_config:/etc/merlin/
    image: op5com/merlin-daemon
volumes:
  ipc:
  merlin_config:
