# Use nss_wrapper to support random UIDs generated by OpenShift
# we always uses nss_wrapper but only modify the passwd file in case we are
# not running with the defauld UID
if [ x"$GID" != x"$NAEMON_GID" -a x"$UID" != x"$NAEMON_UID" ]; then
  cat /etc/passwd | sed "/^$UID/ d" | sed 's/^monitor:/mon_builder:/' > $NSS_WRAPPER_PASSWD
  echo "monitor:x:$UID:0::/opt/monitor:/bin/bash" >> $NSS_WRAPPER_PASSWD
fi
